/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zmiana_koloru;

import java.awt.Color;
import java.awt.Event;
import java.awt.event.KeyEvent;

/**
 *
 * @author drzalajakub
 */
public class MyWindow extends javax.swing.JFrame {

    /**
     * Creates new form MyWindow
     */
    public MyWindow() {
        initComponents();
        jP_color.setBackground(getColour());
        setLocationRelativeTo(null);
        setNumberRGB();
        Hex();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jS_red = new javax.swing.JSlider();
        jS_green = new javax.swing.JSlider();
        jS_blue = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jP_color = new javax.swing.JPanel();
        jL_red = new javax.swing.JLabel();
        jL_green = new javax.swing.JLabel();
        jL_blue = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTF_html = new javax.swing.JTextField();
        jB_miedziany = new javax.swing.JButton();
        jB_seledynowy = new javax.swing.JButton();
        jB_bordowy = new javax.swing.JButton();
        jB_gumiguta = new javax.swing.JButton();
        jB_indygo = new javax.swing.JButton();
        jB_ugor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zmiana koloru");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zmiana koloru tła");

        jLabel2.setText("Red");

        jLabel3.setText("Green");

        jLabel4.setText("Blue");

        jS_red.setMajorTickSpacing(25);
        jS_red.setMaximum(255);
        jS_red.setMinorTickSpacing(1);
        jS_red.setPaintLabels(true);
        jS_red.setPaintTicks(true);
        jS_red.setToolTipText("");
        jS_red.setValue(0);
        jS_red.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jS_redStateChanged(evt);
            }
        });

        jS_green.setMajorTickSpacing(25);
        jS_green.setMaximum(255);
        jS_green.setMinorTickSpacing(1);
        jS_green.setPaintLabels(true);
        jS_green.setPaintTicks(true);
        jS_green.setToolTipText("");
        jS_green.setValue(0);
        jS_green.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jS_greenStateChanged(evt);
            }
        });

        jS_blue.setMajorTickSpacing(25);
        jS_blue.setMaximum(255);
        jS_blue.setMinorTickSpacing(1);
        jS_blue.setPaintLabels(true);
        jS_blue.setPaintTicks(true);
        jS_blue.setToolTipText("");
        jS_blue.setValue(0);
        jS_blue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jS_blueStateChanged(evt);
            }
        });

        jLabel5.setText("Red");

        jLabel6.setText("Blue");

        jLabel7.setText("Green");

        jP_color.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jP_colorLayout = new javax.swing.GroupLayout(jP_color);
        jP_color.setLayout(jP_colorLayout);
        jP_colorLayout.setHorizontalGroup(
            jP_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jP_colorLayout.setVerticalGroup(
            jP_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jL_red.setText("0");

        jL_green.setText("0");

        jL_blue.setText("0");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("HTML");

        jTF_html.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_html.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_htmlActionPerformed(evt);
            }
        });
        jTF_html.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_htmlKeyPressed(evt);
            }
        });

        jB_miedziany.setText("Miedziany");
        jB_miedziany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_miedzianyActionPerformed(evt);
            }
        });

        jB_seledynowy.setText("Seledynowy");
        jB_seledynowy.setToolTipText("Seledynowy");
        jB_seledynowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_seledynowyActionPerformed(evt);
            }
        });

        jB_bordowy.setText("Bordowy");
        jB_bordowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_bordowyActionPerformed(evt);
            }
        });

        jB_gumiguta.setText("Gumiguta");
        jB_gumiguta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_gumigutaActionPerformed(evt);
            }
        });

        jB_indygo.setText("Indygo");
        jB_indygo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_indygoActionPerformed(evt);
            }
        });

        jB_ugor.setText("Ugór");
        jB_ugor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ugorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jL_red, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jL_green, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jL_blue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTF_html, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jP_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jB_seledynowy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB_miedziany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB_bordowy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB_gumiguta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB_indygo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB_ugor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 181, Short.MAX_VALUE))
                            .addComponent(jS_blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jS_red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jS_green, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jS_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jS_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jS_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_red)
                    .addComponent(jL_green)
                    .addComponent(jL_blue)
                    .addComponent(jTF_html, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_seledynowy)
                        .addGap(12, 12, 12)
                        .addComponent(jB_miedziany)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_bordowy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_gumiguta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_indygo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_ugor)
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jS_redStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jS_redStateChanged
        jP_color.setBackground(getColour());
    }//GEN-LAST:event_jS_redStateChanged

    private void jS_greenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jS_greenStateChanged
        jP_color.setBackground(getColour());
    }//GEN-LAST:event_jS_greenStateChanged

    private void jS_blueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jS_blueStateChanged
        jP_color.setBackground(getColour());
    }//GEN-LAST:event_jS_blueStateChanged

    private void jB_bordowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_bordowyActionPerformed
        jS_red.setValue(128);
        jS_green.setValue(0);
        jS_blue.setValue(0);
    }//GEN-LAST:event_jB_bordowyActionPerformed

    private void jB_seledynowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_seledynowyActionPerformed
        jS_red.setValue(172);
        jS_green.setValue(225);
        jS_blue.setValue(175);
    }//GEN-LAST:event_jB_seledynowyActionPerformed

    private void jB_miedzianyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_miedzianyActionPerformed
        jS_red.setValue(160);
        jS_green.setValue(68);
        jS_blue.setValue(43);
    }//GEN-LAST:event_jB_miedzianyActionPerformed

    private void jB_gumigutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_gumigutaActionPerformed
        jS_red.setValue(228);
        jS_green.setValue(155);
        jS_blue.setValue(15);
    }//GEN-LAST:event_jB_gumigutaActionPerformed

    private void jB_indygoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_indygoActionPerformed
        jS_red.setValue(75);
        jS_green.setValue(0);
        jS_blue.setValue(130);
    }//GEN-LAST:event_jB_indygoActionPerformed

    private void jB_ugorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ugorActionPerformed
        jS_red.setValue(185);
        jS_green.setValue(151);
        jS_blue.setValue(102);
    }//GEN-LAST:event_jB_ugorActionPerformed

    private void jTF_htmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_htmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_htmlActionPerformed

    private void jTF_htmlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_htmlKeyPressed

    }//GEN-LAST:event_jTF_htmlKeyPressed
    
    private Color getColour(){
        r = jS_red.getValue();
        g = jS_green.getValue();
        b = jS_blue.getValue();
        Hex();
        setNumberRGB();
        return new Color(r,g,b);      
    }
    
    private void setNumberRGB(){
        jL_red.setText(r+"");
        jL_green.setText(g+"");
        jL_blue.setText(b+"");
    }
    
    private void Hex(){
        jTF_html.setText("#"+Integer.toHexString(r)+Integer.toHexString(g)+Integer.toHexString(b));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyWindow().setVisible(true);
            }
        });
    }
    public int r;
    public int g;
    public int b;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_bordowy;
    private javax.swing.JButton jB_gumiguta;
    private javax.swing.JButton jB_indygo;
    private javax.swing.JButton jB_miedziany;
    private javax.swing.JButton jB_seledynowy;
    private javax.swing.JButton jB_ugor;
    private javax.swing.JLabel jL_blue;
    private javax.swing.JLabel jL_green;
    private javax.swing.JLabel jL_red;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jP_color;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jS_blue;
    private javax.swing.JSlider jS_green;
    private javax.swing.JSlider jS_red;
    private javax.swing.JTextField jTF_html;
    // End of variables declaration//GEN-END:variables
}