/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.przeliczanie_jednostek;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author drzalajakub
 */
public class Przeliczanie_jednostek extends javax.swing.JFrame {

    /**
     * Creates new form Przeliczanie_jednostek
     */
    public Przeliczanie_jednostek() {
        initComponents();
        setLocationRelativeTo(null);
        a = new File("Plik.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDIalog_historia = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTP_temp = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTP_odl = new javax.swing.JTextPane();
        jDialog_oprogramie = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jS_c = new javax.swing.JSpinner();
        jB_k = new javax.swing.JButton();
        jB_f = new javax.swing.JButton();
        jL_wynikTemperatura = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jS_m = new javax.swing.JSpinner();
        jB_km = new javax.swing.JButton();
        jB_cm = new javax.swing.JButton();
        jB_dm = new javax.swing.JButton();
        jL_wynikOdleglosc = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        JDIalog_historia.setTitle("Historia");
        JDIalog_historia.setPreferredSize(new java.awt.Dimension(421, 270));
        JDIalog_historia.setResizable(false);

        jPanel4.setPreferredSize(new java.awt.Dimension(300, 500));

        jTP_temp.setEditable(false);
        jScrollPane1.setViewportView(jTP_temp);

        jTP_odl.setEditable(false);
        jScrollPane4.setViewportView(jTP_odl);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane4)
        );

        javax.swing.GroupLayout JDIalog_historiaLayout = new javax.swing.GroupLayout(JDIalog_historia.getContentPane());
        JDIalog_historia.getContentPane().setLayout(JDIalog_historiaLayout);
        JDIalog_historiaLayout.setHorizontalGroup(
            JDIalog_historiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );
        JDIalog_historiaLayout.setVerticalGroup(
            JDIalog_historiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        jDialog_oprogramie.setTitle("O Programie");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel3.setText("Program oblicza temperaturę oraz odległość");

        javax.swing.GroupLayout jDialog_oprogramieLayout = new javax.swing.GroupLayout(jDialog_oprogramie.getContentPane());
        jDialog_oprogramie.getContentPane().setLayout(jDialog_oprogramieLayout);
        jDialog_oprogramieLayout.setHorizontalGroup(
            jDialog_oprogramieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_oprogramieLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(47, 47, 47))
        );
        jDialog_oprogramieLayout.setVerticalGroup(
            jDialog_oprogramieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_oprogramieLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Podaj temperature w celsujszach:");

        jB_k.setText("Zamień na kelwiny");
        jB_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_kActionPerformed(evt);
            }
        });

        jB_f.setText("Zamień na fahrenheity");
        jB_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_fActionPerformed(evt);
            }
        });

        jL_wynikTemperatura.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jL_wynikTemperatura.setText("Wynik");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jB_k)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_f))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jS_c, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jL_wynikTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jS_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jL_wynikTemperatura)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_k, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_f, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Temperatura", jPanel1);

        jLabel1.setText("Podaj wartość w metrach:");

        jB_km.setText("Zamień na km");
        jB_km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_kmActionPerformed(evt);
            }
        });

        jB_cm.setText("Zamień na cm");
        jB_cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cmActionPerformed(evt);
            }
        });

        jB_dm.setText("Zamień na dm");
        jB_dm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_dmActionPerformed(evt);
            }
        });

        jL_wynikOdleglosc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jL_wynikOdleglosc.setText("Wynik");
        jL_wynikOdleglosc.setToolTipText("");
        jL_wynikOdleglosc.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_wynikOdleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jS_m, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jB_km)
                        .addGap(18, 18, 18)
                        .addComponent(jB_cm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_dm)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jS_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jL_wynikOdleglosc)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_km)
                    .addComponent(jB_dm)
                    .addComponent(jB_cm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Odległość", jPanel2);

        jMenu1.setText("Pliki");
        jMenu1.setPreferredSize(new java.awt.Dimension(200, 23));

        jMenuItem1.setText("Pokaż historię");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Zamknij program");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("O Programie");
        jMenu2.setPreferredSize(new java.awt.Dimension(200, 23));

        jMenuItem3.setText("O Programie");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jDialog_oprogramie.setVisible(true);
        jDialog_oprogramie.setSize(350,200);
        jDialog_oprogramie.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jB_kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_kmActionPerformed
        float m = (int)jS_m.getValue();
        float km = m /1000;
        jL_wynikOdleglosc.setText(km+"");
        try {
            FileWriter fw = new FileWriter(a, true);
            fw.write("o;"+m+"m;"+km+"km"+"\n");
            fw.close();
        }
        catch (IOException ex){
            Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jB_kmActionPerformed

    private void jB_cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cmActionPerformed
        float m = (int)jS_m.getValue();
        float cm = m *100;
        jL_wynikOdleglosc.setText(cm+"");
        try {
            FileWriter fw = new FileWriter(a, true);
            fw.write("o;"+m+"m;"+cm+"cm"+"\n");
            fw.close();
        }
        catch (IOException ex){
            Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jB_cmActionPerformed

    private void jB_dmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_dmActionPerformed
        float m = (int)jS_m.getValue();
        float dm = m *10;
        jL_wynikOdleglosc.setText(dm+"");
        try {
            FileWriter fw = new FileWriter(a, true);
            fw.write("o;"+m+"m;"+dm+"dm"+"\n");
            fw.close();
        }
        catch (IOException ex){
            Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jB_dmActionPerformed

    private void jB_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_kActionPerformed
         float c = (int)jS_c.getValue();
         float k = c + 273;
        jL_wynikTemperatura.setText(k+"");
        try {
            FileWriter fw = new FileWriter(a, true);
            fw.write("t;"+c+"c;"+k+"k"+"\n");
            fw.close();
        }
        catch (IOException ex){
            Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jB_kActionPerformed

    private void jB_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_fActionPerformed
        float c = (int)jS_c.getValue();
        float f = (c * 9/5) + 32 ;
        jL_wynikTemperatura.setText(f+"");
        try {
            FileWriter fw = new FileWriter(a, true);
            fw.write("t;"+c+"c;"+f+"f"+"\n");
            fw.close();
        }
        catch (IOException ex){
            Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jB_fActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDIalog_historia.setVisible(true);
        JDIalog_historia.setSize(300,500);
        JDIalog_historia.setLocationRelativeTo(null);
        try{
            Scanner sc = new Scanner(a);
            String data ="";
            while(sc.hasNext()){
                data+=sc.nextLine()+"\n";     
            }       
            jTP_temp.setText(data);
        }
        catch (FileNotFoundException ex){
            Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Przeliczanie_jednostek().setVisible(true);
            }
        });
    }
    private File a;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JDIalog_historia;
    private javax.swing.JButton jB_cm;
    private javax.swing.JButton jB_dm;
    private javax.swing.JButton jB_f;
    private javax.swing.JButton jB_k;
    private javax.swing.JButton jB_km;
    private javax.swing.JDialog jDialog_oprogramie;
    private javax.swing.JLabel jL_wynikOdleglosc;
    private javax.swing.JLabel jL_wynikTemperatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner jS_c;
    private javax.swing.JSpinner jS_m;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextPane jTP_odl;
    private javax.swing.JTextPane jTP_temp;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
