/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projekt;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author drzalajakub
 */
public class Program extends javax.swing.JFrame {

    /**
     * Creates new form Program
     */
    public Program() {
        initComponents();
        setLocationRelativeTo(null);
        a = new File("Plik.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTF_imie = new javax.swing.JTextField();
        jTF_nazwisko = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCB_wiek = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTA_wynik = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTA_o_sobie = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jRB_miasto = new javax.swing.JRadioButton();
        jRB_poza = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMI_zapis = new javax.swing.JMenuItem();
        jMI_odczyt = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMI_zamkniecie = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projekt");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jPanel1.setName("Projekt"); // NOI18N

        jLabel1.setText("Podaj imię:");

        jLabel2.setText("Podaj nazwisko:");

        jTF_imie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_imieActionPerformed(evt);
            }
        });

        jLabel3.setText("Ile masz lat?");

        jCB_wiek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poniżej 18", "18", "Powyżej 18" }));
        jCB_wiek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCB_wiek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_wiekActionPerformed(evt);
            }
        });

        jLabel4.setText("Napisz coś o sobie:");

        jTA_wynik.setEditable(false);
        jTA_wynik.setColumns(20);
        jTA_wynik.setRows(5);
        jScrollPane3.setViewportView(jTA_wynik);

        jTA_o_sobie.setColumns(20);
        jTA_o_sobie.setRows(5);
        jScrollPane4.setViewportView(jTA_o_sobie);

        jLabel6.setText("Mieszkasz:");

        jRB_miasto.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(jRB_miasto);
        jRB_miasto.setText("W mieście");

        jRB_poza.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(jRB_poza);
        jRB_poza.setText("Poza miastem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_imie)
                            .addComponent(jTF_nazwisko)
                            .addComponent(jCB_wiek, 0, 167, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_miasto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_poza))
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTF_imie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTF_nazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jCB_wiek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jRB_miasto)
                            .addComponent(jRB_poza))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("Plik");
        jMenu1.setMaximumSize(new java.awt.Dimension(200, 32767));

        jMI_zapis.setText("Zapisz");
        jMI_zapis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_zapisActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_zapis);

        jMI_odczyt.setText("Wczytaj");
        jMI_odczyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_odczytActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_odczyt);
        jMenu1.add(jSeparator1);

        jMI_zamkniecie.setText("Zamknij program");
        jMI_zamkniecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_zamkniecieActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_zamkniecie);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edycja");
        jMenu2.setMaximumSize(new java.awt.Dimension(200, 32767));

        jMenuItem4.setText("Zmień czcionkę");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenu4.setText("Zmień tło");

        jMenuItem1.setText("Podstawowe");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Alternatywne");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("O programie");
        jMenu3.setMaximumSize(new java.awt.Dimension(200, 32767));

        jMenuItem6.setText("O programie");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Pomoc");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCB_wiekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_wiekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_wiekActionPerformed

    private void jMI_zapisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_zapisActionPerformed
        String imie = jTF_imie.getText();
        String nazwisko = jTF_nazwisko.getText();
        String wiek = (String)jCB_wiek.getSelectedItem();
        String o_sobie = jTA_o_sobie.getText();
        String miejsce;
        if(jRB_miasto.isSelected()){
            miejsce = "Miasto";
        }
        else{
            miejsce = "Poza miastem";
        }
        try {
            FileWriter fw = new FileWriter(a, true);
            fw.write(imie+";"+nazwisko+";"+wiek+";"+miejsce+";"+o_sobie+"\n");
            jTA_wynik.setText("");
            fw.close();
        }
        catch (IOException ex){
            Logger.getLogger(Program.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jMI_zapisActionPerformed

    private void jMI_zamkniecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_zamkniecieActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMI_zamkniecieActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        o_programie f2=new o_programie();
        f2.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jTF_imie.setFont(new java.awt.Font("SansSerif", 1, 11));
        jTF_nazwisko.setFont(new java.awt.Font("SansSerif", 1, 11));
        jCB_wiek.setFont(new java.awt.Font("SansSerif", 1, 11));
        jRB_miasto.setFont(new java.awt.Font("SansSerif", 1, 11));
        jRB_poza.setFont(new java.awt.Font("SansSerif", 1, 11));
        jTA_o_sobie.setFont(new java.awt.Font("SansSerif", 1, 11));
        jTA_wynik.setFont(new java.awt.Font("SansSerif", 1, 11));
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jPanel1.setBackground(new java.awt.Color(204,255,204));
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jPanel1.setBackground(new java.awt.Color(100, 100, 100));
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTF_imieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_imieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_imieActionPerformed

    private void jMI_odczytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_odczytActionPerformed
        try{
            Scanner sc = new Scanner(a);
            String data ="";
            while(sc.hasNext()){
                data+=sc.nextLine()+"\n";     
            }       
            jTA_wynik.setText(data);
        }
        catch (FileNotFoundException ex){
            Logger.getLogger(Program.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jMI_odczytActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program().setVisible(true);
            }
        });
    }
    private File a;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jCB_wiek;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMI_odczyt;
    private javax.swing.JMenuItem jMI_zamkniecie;
    private javax.swing.JMenuItem jMI_zapis;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRB_miasto;
    private javax.swing.JRadioButton jRB_poza;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTA_o_sobie;
    private javax.swing.JTextArea jTA_wynik;
    private javax.swing.JTextField jTF_imie;
    private javax.swing.JTextField jTF_nazwisko;
    // End of variables declaration//GEN-END:variables
}
